name: Test MyCLI Setup

on:
  push:
    branches:
      - main
      - feature/*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
